name: build-on-linux-arm32v7

on:
  workflow_dispatch:

env:
  USE_NATIVE_VERSION: v0.0.0
  UNAMESPACER: linux-arm32v7

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Download sources
        run: |
          bash scripts/build.sh -d

      - name: Upload sources
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  build_targets_on_linux_arm32v7_cross:
    name: Build cross
    runs-on: ubuntu-24.04-arm
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Build
        id: build
        run: |
          docker run --rm \
            --volume "${PWD}:/build" \
            arm32v7/alpine:latest \
            /bin/sh -c '
              apk add --no-cache \
                coreutils \
                curl \
                bzip2 \
                xz \
                make \
                bison \
                rsync \
                patch \
                perl \
                flex \
                g++ && \
              cd /build && \
              sh scripts/build.sh \
                -LDP \
                -T "${{ matrix.targets }}"'

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets }}
          path: dist
