name: releases-on-darwin-amd64

on:
  push:
    tags:
      - "v*"

env:
  UNAMESPACER: darwin-amd64

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.get_all_targets.outputs.TARGETS }}
    steps:
      - uses: actions/checkout@v4

      - name: Get all targets
        id: get_all_targets
        run: |
          declare -a arr=()
          while IFS= read -r line; do
          if [ -z "$line" ] || [ "${line:0:1}" == "#" ]; then
            continue
          fi
          arr+=("$line")
          done < scripts/triples.txt
          printf -v json '"%s",' "${arr[@]}"
          json="[${json%,}]"
          echo "TARGETS=$json" >> $GITHUB_OUTPUT

      - name: Download sources
        run: |
          bash scripts/build.sh -d

      - name: Upload sources
        uses: actions/upload-artifact@v4
        with:
          name: sources
          path: sources

  releases_targets_on_macos_amd64:
    name: Build
    runs-on: macos-13
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        targets: ${{ fromJSON(needs.init.outputs.TARGETS) }}
    steps:
      - uses: actions/checkout@v4

      - name: Init Dependencies
        run: |
          brew install \
            make \
            gnu-sed \
            gawk \
            gpatch \
            coreutils \
            findutils \
            gcc@14 \
            perl \
            libtool

      - uses: actions/download-artifact@v4
        with:
          name: sources
          path: sources

      - name: Build
        id: build
        run: |
          export CROSS_DIST_NAME_SUFFIX="-${{ env.UNAMESPACER }}"
          bash scripts/build.sh \
            -LDP \
            -c "gcc-14" -x "g++-14" \
            -a \
            -T "${{ matrix.targets }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*.*